### ISSUE TITLE
Teaming up with hatchery

### ISSUE THREAD

**Issue by machinekoder** [Noam-Dori/ros-integrate#1]
Just wondering, is this project related to [hatchery](https://github.com/duckietown/hatchery)? If not, I think it would be great to team up to improve ROS support in IntelliJ more quickly.

I'm using CLion with the Hatchery plugin so far, but what I'm missing is catkin build support. roslaunch support would be nice as well.

**Comment by Noam-Dori** [comment]
While both plugins do help development on ROS, they are not related and developed independently.

The idea behind this plugin is to create the entire ROS model by starting from the simpler components (messages) then building up towards more complex components (such as workspaces and launch/test files).

support for launch/test files is defiantly something to be added in the future, but I first want to take care of the model they rely on.

What do you mean by catkin build support? What exactly would you like to see with catkin included in the plugin?
