### ISSUE TITLE
Avoid whole computer indexing

### ISSUE THREAD

**Issue by remi2257** [Noam-Dori/ros-integrate#30]
**Feature:**
I would like PyCharm to not index files when Workspace (Langugages & Framworks > ROS) is not filled

**Background**
The plugin always want to index. It starts to index my whole computer as soon as I create a project because initially, the workspace is empty which corresponds to the PC's root (I guess)
As it is not possible to enable/disable plugins for one specific project, ROS Support is always enable on my PyCharm and each time I create a new project, my computer almost freeze because PyCharm is indexing everything

**Details**
Can you add an option/condition which will allow set a new external library only if the user set one :) ?

Cheers

**Comment by Noam-Dori** [comment]
fixed

**Comment by remi2257** [comment]
Thank you sir :)
