### ISSUE TITLE
Wrongly take my junit run button.

### ISSUE THREAD

**Issue by hliao** [Noam-Dori/ros-integrate#5]
Hi 

I am using intellij for java, and all the junit test case button had been replace by your plugin , when I click on it ,it create a test run with the cute icon , which actually I want to run my test case via junit. please help fix it, it is really boring.  

BR
Xavier

**Comment by hliao** [comment]
And something really interesting , I didn't install this plugin , . maybe it is not a bug from your side, please help check.

**Comment by Noam-Dori** [comment]
What icon is shown? Could you post a picture of it? I am afraid I don't understand what icon you refer to when you say "cute icon". Moreover, if you didn't install this plugin, its highly unlikely that this plugin is the cause of it.
