### ISSUE TITLE
Launch file support

### ISSUE THREAD

**Issue by peci1** [Noam-Dori/ros-integrate#61]
Do you plan to support autocompletion and package resolving in launch files?

One can use 

```
<launch xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://gist.githubusercontent.com/nalt/dfa2abc9d2e3ae4feb82ca5608090387/raw/roslaunch.xsd">
```

but that is a half-baked solution...

**Comment by Noam-Dori** [comment]
Being such a fundemental component of ROS development, it is only a matter of time until this plugin will also support launch files

To be more specific, I plan to start working on it once I have the ROS infrastructure (which is only missing CMake and toolchain support) complete

While there is no real feature list yet, the plugin will offer support similar to package.xml files and run/debug capabilities

**Comment by peci1** [comment]
Thanks! Looking forward for it :)
