### ISSUE TITLE
Unable to save plugin settings: The plugin ros-integrate failed to save settings and has been disabled. Please restart CLion

### ISSUE THREAD

**Issue by perisage** [Noam-Dori/ros-integrate#70]
**Describe the bug**
*just install ros plugin and restart CLion, the error occurred as the following:*
Unable to save plugin settings: The plugin ros-integrate failed to save settings and has been disabled. Please restart CLion

**To Reproduce**
*just install ros plugin and restart CLion*

**Environment Information:**
 - OS: *Ubuntu 20.04*
 - IDE: *CLion 2021.2.2*
 - Plugin Version: * 0.1.6*
 - Related Plugins: *No*

**Additional context**
*Add any other context about the problem here.*

**Comment by Noam-Dori** [comment]
I remember seeing this error message when I dealt with issue #68 . From what I said when that issue was fixed:

> ... all plugin services (save for few plugin components) were not loaded by the plugin.xml.
> This was caused by an improper use of XInclude in the plugin.xml. XInclude, which allows importing tags from other documents, should be used at the root on the including document, and not deeper within the tree (which I did). Fixing this problem allowed the components to load.
>
> The fix should be available for the next release, 0.1.7, and is already available here.
>
> Fix was tested on IntelliJ IDEA Community 2021.2 on Windows 10.

If you are up for it, you can [install the plugin from source](https://github.com/Noam-Dori/ros-integrate/wiki/Working-From-Source#guide---install-ros-support-from-source) to apply the fix right now.

**Comment by perisage** [comment]
when the fixed version 0.1.7 will be released? The plugin version on the jetbrains plugin market is also 0.1.6 and 0.1.7 is stiil unavailable.

**Comment by Noam-Dori** [comment]
Closed due to inactivity
